# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate a GARCH(p,q) realization
NULL

garch_sim_cpp <- function(n, alpha0, alpha, beta, eps, burn = 500L) {
    .Call(`_tswge2_garch_sim_cpp`, n, alpha0, alpha, beta, eps, burn)
}

